[API_KEYS]
OPENAI_API_KEY = "OPENAI_API_KEY"
GOOGLE_API_KEY = "GOOGLE_API_KEY"

[LANGSMITH]
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="LANGCHAIN_API_KEY"
LANGCHAIN_PROJECT="research-ai-chatbot"

[PROJECT]
ENVIRONMENT = "development"
DEBUG = true
HOST = "localhost"
PORT = 5000

[VECTOR_STORE]
CHROMA_PERSIST_DIRECTORY = "./chroma_db"
COLLECTION_NAME = "research_documents"

[MODEL_SETTINGS]
TEMPERATURE = 0.7
MAX_TOKENS = 2000
MODEL_NAME = "gpt-3.5-turbo"
GEMINI_MODEL = "gemini-2.0-flash"

[DOCUMENT_PROCESSING]
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

[FLASK]
FLASK_ENV = "development"
FLASK_DEBUG = 1
APP_PORT = 5000